// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qiwi.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddAccountRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAccountRequest) Reset()         { *m = AddAccountRequest{} }
func (m *AddAccountRequest) String() string { return proto.CompactTextString(m) }
func (*AddAccountRequest) ProtoMessage()    {}
func (*AddAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{0}
}

func (m *AddAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAccountRequest.Unmarshal(m, b)
}
func (m *AddAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAccountRequest.Marshal(b, m, deterministic)
}
func (m *AddAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAccountRequest.Merge(m, src)
}
func (m *AddAccountRequest) XXX_Size() int {
	return xxx_messageInfo_AddAccountRequest.Size(m)
}
func (m *AddAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAccountRequest proto.InternalMessageInfo

func (m *AddAccountRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type AddAccountResponse struct {
	ContractID           int64    `protobuf:"varint,1,opt,name=contractID,proto3" json:"contractID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAccountResponse) Reset()         { *m = AddAccountResponse{} }
func (m *AddAccountResponse) String() string { return proto.CompactTextString(m) }
func (*AddAccountResponse) ProtoMessage()    {}
func (*AddAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{1}
}

func (m *AddAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAccountResponse.Unmarshal(m, b)
}
func (m *AddAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAccountResponse.Marshal(b, m, deterministic)
}
func (m *AddAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAccountResponse.Merge(m, src)
}
func (m *AddAccountResponse) XXX_Size() int {
	return xxx_messageInfo_AddAccountResponse.Size(m)
}
func (m *AddAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddAccountResponse proto.InternalMessageInfo

func (m *AddAccountResponse) GetContractID() int64 {
	if m != nil {
		return m.ContractID
	}
	return 0
}

type ListAccountsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{2}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

type ListAccountsResponse struct {
	ContractIDs          []int64  `protobuf:"varint,1,rep,packed,name=contractIDs,proto3" json:"contractIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsResponse) Reset()         { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()    {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{3}
}

func (m *ListAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsResponse.Unmarshal(m, b)
}
func (m *ListAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsResponse.Marshal(b, m, deterministic)
}
func (m *ListAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsResponse.Merge(m, src)
}
func (m *ListAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsResponse.Size(m)
}
func (m *ListAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsResponse proto.InternalMessageInfo

func (m *ListAccountsResponse) GetContractIDs() []int64 {
	if m != nil {
		return m.ContractIDs
	}
	return nil
}

type GetAccountBalancesRequest struct {
	ContractID           int64    `protobuf:"varint,1,opt,name=contractID,proto3" json:"contractID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountBalancesRequest) Reset()         { *m = GetAccountBalancesRequest{} }
func (m *GetAccountBalancesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountBalancesRequest) ProtoMessage()    {}
func (*GetAccountBalancesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{4}
}

func (m *GetAccountBalancesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountBalancesRequest.Unmarshal(m, b)
}
func (m *GetAccountBalancesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountBalancesRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountBalancesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountBalancesRequest.Merge(m, src)
}
func (m *GetAccountBalancesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountBalancesRequest.Size(m)
}
func (m *GetAccountBalancesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountBalancesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountBalancesRequest proto.InternalMessageInfo

func (m *GetAccountBalancesRequest) GetContractID() int64 {
	if m != nil {
		return m.ContractID
	}
	return 0
}

type GetAccountBalancesResponse struct {
	Balances             map[string]float64 `protobuf:"bytes,1,rep,name=balances,proto3" json:"balances,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *GetAccountBalancesResponse) Reset()         { *m = GetAccountBalancesResponse{} }
func (m *GetAccountBalancesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountBalancesResponse) ProtoMessage()    {}
func (*GetAccountBalancesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{5}
}

func (m *GetAccountBalancesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountBalancesResponse.Unmarshal(m, b)
}
func (m *GetAccountBalancesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountBalancesResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountBalancesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountBalancesResponse.Merge(m, src)
}
func (m *GetAccountBalancesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountBalancesResponse.Size(m)
}
func (m *GetAccountBalancesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountBalancesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountBalancesResponse proto.InternalMessageInfo

func (m *GetAccountBalancesResponse) GetBalances() map[string]float64 {
	if m != nil {
		return m.Balances
	}
	return nil
}

type SendMoneyToQiwiRequest struct {
	SenderContractID     int64    `protobuf:"varint,1,opt,name=senderContractID,proto3" json:"senderContractID,omitempty"`
	ReceiverContractID   string   `protobuf:"bytes,2,opt,name=receiverContractID,proto3" json:"receiverContractID,omitempty"`
	Currency             string   `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount               float64  `protobuf:"fixed64,4,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMoneyToQiwiRequest) Reset()         { *m = SendMoneyToQiwiRequest{} }
func (m *SendMoneyToQiwiRequest) String() string { return proto.CompactTextString(m) }
func (*SendMoneyToQiwiRequest) ProtoMessage()    {}
func (*SendMoneyToQiwiRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{6}
}

func (m *SendMoneyToQiwiRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMoneyToQiwiRequest.Unmarshal(m, b)
}
func (m *SendMoneyToQiwiRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMoneyToQiwiRequest.Marshal(b, m, deterministic)
}
func (m *SendMoneyToQiwiRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMoneyToQiwiRequest.Merge(m, src)
}
func (m *SendMoneyToQiwiRequest) XXX_Size() int {
	return xxx_messageInfo_SendMoneyToQiwiRequest.Size(m)
}
func (m *SendMoneyToQiwiRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMoneyToQiwiRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendMoneyToQiwiRequest proto.InternalMessageInfo

func (m *SendMoneyToQiwiRequest) GetSenderContractID() int64 {
	if m != nil {
		return m.SenderContractID
	}
	return 0
}

func (m *SendMoneyToQiwiRequest) GetReceiverContractID() string {
	if m != nil {
		return m.ReceiverContractID
	}
	return ""
}

func (m *SendMoneyToQiwiRequest) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *SendMoneyToQiwiRequest) GetAmount() float64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type SendMoneyToQiwiResponse struct {
	Status               string   `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendMoneyToQiwiResponse) Reset()         { *m = SendMoneyToQiwiResponse{} }
func (m *SendMoneyToQiwiResponse) String() string { return proto.CompactTextString(m) }
func (*SendMoneyToQiwiResponse) ProtoMessage()    {}
func (*SendMoneyToQiwiResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{7}
}

func (m *SendMoneyToQiwiResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendMoneyToQiwiResponse.Unmarshal(m, b)
}
func (m *SendMoneyToQiwiResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendMoneyToQiwiResponse.Marshal(b, m, deterministic)
}
func (m *SendMoneyToQiwiResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendMoneyToQiwiResponse.Merge(m, src)
}
func (m *SendMoneyToQiwiResponse) XXX_Size() int {
	return xxx_messageInfo_SendMoneyToQiwiResponse.Size(m)
}
func (m *SendMoneyToQiwiResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendMoneyToQiwiResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendMoneyToQiwiResponse proto.InternalMessageInfo

func (m *SendMoneyToQiwiResponse) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func init() {
	proto.RegisterType((*AddAccountRequest)(nil), "protobuf.AddAccountRequest")
	proto.RegisterType((*AddAccountResponse)(nil), "protobuf.AddAccountResponse")
	proto.RegisterType((*ListAccountsRequest)(nil), "protobuf.ListAccountsRequest")
	proto.RegisterType((*ListAccountsResponse)(nil), "protobuf.ListAccountsResponse")
	proto.RegisterType((*GetAccountBalancesRequest)(nil), "protobuf.GetAccountBalancesRequest")
	proto.RegisterType((*GetAccountBalancesResponse)(nil), "protobuf.GetAccountBalancesResponse")
	proto.RegisterMapType((map[string]float64)(nil), "protobuf.GetAccountBalancesResponse.BalancesEntry")
	proto.RegisterType((*SendMoneyToQiwiRequest)(nil), "protobuf.SendMoneyToQiwiRequest")
	proto.RegisterType((*SendMoneyToQiwiResponse)(nil), "protobuf.SendMoneyToQiwiResponse")
}

func init() { proto.RegisterFile("qiwi.proto", fileDescriptor_4cdcb2c5ad188f99) }

var fileDescriptor_4cdcb2c5ad188f99 = []byte{
	// 433 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xed, 0xda, 0x25, 0x4a, 0xa7, 0x54, 0x94, 0xa1, 0x04, 0x63, 0xa0, 0x32, 0x0b, 0x87, 0xc0,
	0xc1, 0x12, 0x81, 0x43, 0x45, 0x4f, 0x0d, 0x20, 0x54, 0x89, 0x8f, 0x62, 0x38, 0x70, 0x75, 0xd6,
	0x8b, 0x64, 0x35, 0xec, 0x26, 0xde, 0x75, 0x22, 0xff, 0x23, 0xf8, 0x55, 0xfc, 0x15, 0x64, 0x7b,
	0x1d, 0x3b, 0xb1, 0x13, 0x38, 0xd9, 0xf3, 0xe6, 0xbd, 0xf9, 0x78, 0x3b, 0x00, 0xf3, 0x78, 0x19,
	0xfb, 0xb3, 0x44, 0x6a, 0x89, 0xfd, 0xe2, 0x33, 0x49, 0x7f, 0xd0, 0x67, 0x70, 0xfb, 0x22, 0x8a,
	0x2e, 0x18, 0x93, 0xa9, 0xd0, 0x01, 0x9f, 0xa7, 0x5c, 0x69, 0x3c, 0x81, 0x1b, 0x5a, 0x5e, 0x73,
	0xe1, 0x10, 0x8f, 0x0c, 0x0f, 0x82, 0x32, 0xa0, 0xaf, 0x00, 0x9b, 0x54, 0x35, 0x93, 0x42, 0x71,
	0x3c, 0x05, 0x60, 0x52, 0xe8, 0x24, 0x64, 0xfa, 0xf2, 0x6d, 0x21, 0xb0, 0x83, 0x06, 0x42, 0xef,
	0xc2, 0x9d, 0x0f, 0xb1, 0xd2, 0x46, 0xa6, 0x4c, 0x0b, 0x7a, 0x06, 0x27, 0xeb, 0xb0, 0x29, 0xe7,
	0xc1, 0x61, 0x2d, 0x56, 0x0e, 0xf1, 0xec, 0xa1, 0x1d, 0x34, 0x21, 0x7a, 0x0e, 0xf7, 0xdf, 0xf3,
	0x4a, 0x38, 0x0e, 0xa7, 0xa1, 0x60, 0xbc, 0x2a, 0xfb, 0xcf, 0x69, 0x7e, 0x13, 0x70, 0xbb, 0xd4,
	0xa6, 0xfb, 0x27, 0xe8, 0x4f, 0x0c, 0x56, 0xb4, 0x3e, 0x1c, 0x8d, 0xfc, 0xca, 0x2a, 0x7f, 0xbb,
	0xce, 0xaf, 0x80, 0x77, 0x42, 0x27, 0x59, 0xb0, 0xaa, 0xe1, 0x9e, 0xc3, 0xd1, 0x5a, 0x0a, 0x8f,
	0xc1, 0xbe, 0xe6, 0x99, 0xf1, 0x35, 0xff, 0xcd, 0xbd, 0x5e, 0x84, 0xd3, 0x94, 0x3b, 0x96, 0x47,
	0x86, 0x24, 0x28, 0x83, 0xd7, 0xd6, 0x19, 0xa1, 0xbf, 0x08, 0x0c, 0xbe, 0x72, 0x11, 0x7d, 0x94,
	0x82, 0x67, 0xdf, 0xe4, 0x97, 0x78, 0x19, 0x57, 0x6b, 0x3e, 0x87, 0x63, 0xc5, 0x45, 0xc4, 0x93,
	0x37, 0x9b, 0xcb, 0xb6, 0x70, 0xf4, 0x01, 0x13, 0xce, 0x78, 0xbc, 0x58, 0x63, 0x5b, 0xc5, 0x04,
	0x1d, 0x19, 0x74, 0xa1, 0xcf, 0xd2, 0x24, 0xe1, 0x82, 0x65, 0x8e, 0x5d, 0xb0, 0x56, 0x31, 0x0e,
	0xa0, 0x17, 0xfe, 0xcc, 0x1d, 0x70, 0xf6, 0x8b, 0x69, 0x4d, 0x44, 0x5f, 0xc0, 0xbd, 0xd6, 0xa4,
	0xc6, 0xd2, 0x01, 0xf4, 0x94, 0x0e, 0x75, 0xaa, 0xcc, 0xd2, 0x26, 0x1a, 0xfd, 0xb1, 0x60, 0x3f,
	0x27, 0xe2, 0x25, 0x40, 0x7d, 0x56, 0xf8, 0xa0, 0xf6, 0xbb, 0x75, 0x97, 0xee, 0xc3, 0xee, 0x64,
	0xd9, 0x89, 0xee, 0xe1, 0x67, 0xb8, 0xd9, 0x3c, 0x2a, 0x7c, 0x54, 0xf3, 0x3b, 0x6e, 0xd0, 0x3d,
	0xdd, 0x96, 0x5e, 0x15, 0x0c, 0x01, 0xdb, 0xaf, 0x8e, 0x4f, 0x76, 0xdf, 0x44, 0x59, 0xfc, 0xe9,
	0xff, 0x1c, 0x0e, 0xdd, 0xc3, 0xef, 0x70, 0x6b, 0xc3, 0x3a, 0xf4, 0x6a, 0x69, 0xf7, 0xfb, 0xbb,
	0x8f, 0x77, 0x30, 0xaa, 0xca, 0xe3, 0xa3, 0xf1, 0x41, 0x8e, 0x5c, 0xe5, 0xcc, 0x2b, 0x32, 0xe9,
	0x15, 0x92, 0x97, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe1, 0xfa, 0x83, 0x9a, 0x08, 0x04, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QiwiClient is the client API for Qiwi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QiwiClient interface {
	AddAccount(ctx context.Context, in *AddAccountRequest, opts ...grpc.CallOption) (*AddAccountResponse, error)
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
	GetAccountBalances(ctx context.Context, in *GetAccountBalancesRequest, opts ...grpc.CallOption) (*GetAccountBalancesResponse, error)
	SendMoneyToQiwi(ctx context.Context, in *SendMoneyToQiwiRequest, opts ...grpc.CallOption) (*SendMoneyToQiwiResponse, error)
}

type qiwiClient struct {
	cc *grpc.ClientConn
}

func NewQiwiClient(cc *grpc.ClientConn) QiwiClient {
	return &qiwiClient{cc}
}

func (c *qiwiClient) AddAccount(ctx context.Context, in *AddAccountRequest, opts ...grpc.CallOption) (*AddAccountResponse, error) {
	out := new(AddAccountResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Qiwi/AddAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qiwiClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Qiwi/ListAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qiwiClient) GetAccountBalances(ctx context.Context, in *GetAccountBalancesRequest, opts ...grpc.CallOption) (*GetAccountBalancesResponse, error) {
	out := new(GetAccountBalancesResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Qiwi/GetAccountBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qiwiClient) SendMoneyToQiwi(ctx context.Context, in *SendMoneyToQiwiRequest, opts ...grpc.CallOption) (*SendMoneyToQiwiResponse, error) {
	out := new(SendMoneyToQiwiResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Qiwi/SendMoneyToQiwi", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QiwiServer is the server API for Qiwi service.
type QiwiServer interface {
	AddAccount(context.Context, *AddAccountRequest) (*AddAccountResponse, error)
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	GetAccountBalances(context.Context, *GetAccountBalancesRequest) (*GetAccountBalancesResponse, error)
	SendMoneyToQiwi(context.Context, *SendMoneyToQiwiRequest) (*SendMoneyToQiwiResponse, error)
}

func RegisterQiwiServer(s *grpc.Server, srv QiwiServer) {
	s.RegisterService(&_Qiwi_serviceDesc, srv)
}

func _Qiwi_AddAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QiwiServer).AddAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Qiwi/AddAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QiwiServer).AddAccount(ctx, req.(*AddAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qiwi_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QiwiServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Qiwi/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QiwiServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qiwi_GetAccountBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QiwiServer).GetAccountBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Qiwi/GetAccountBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QiwiServer).GetAccountBalances(ctx, req.(*GetAccountBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qiwi_SendMoneyToQiwi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMoneyToQiwiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QiwiServer).SendMoneyToQiwi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Qiwi/SendMoneyToQiwi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QiwiServer).SendMoneyToQiwi(ctx, req.(*SendMoneyToQiwiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Qiwi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Qiwi",
	HandlerType: (*QiwiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAccount",
			Handler:    _Qiwi_AddAccount_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _Qiwi_ListAccounts_Handler,
		},
		{
			MethodName: "GetAccountBalances",
			Handler:    _Qiwi_GetAccountBalances_Handler,
		},
		{
			MethodName: "SendMoneyToQiwi",
			Handler:    _Qiwi_SendMoneyToQiwi_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qiwi.proto",
}
