// Code generated by protoc-gen-go. DO NOT EDIT.
// source: qiwi.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddAccountRequest struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	ContractID           string   `protobuf:"bytes,2,opt,name=contractID,proto3" json:"contractID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAccountRequest) Reset()         { *m = AddAccountRequest{} }
func (m *AddAccountRequest) String() string { return proto.CompactTextString(m) }
func (*AddAccountRequest) ProtoMessage()    {}
func (*AddAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{0}
}

func (m *AddAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAccountRequest.Unmarshal(m, b)
}
func (m *AddAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAccountRequest.Marshal(b, m, deterministic)
}
func (m *AddAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAccountRequest.Merge(m, src)
}
func (m *AddAccountRequest) XXX_Size() int {
	return xxx_messageInfo_AddAccountRequest.Size(m)
}
func (m *AddAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddAccountRequest proto.InternalMessageInfo

func (m *AddAccountRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AddAccountRequest) GetContractID() string {
	if m != nil {
		return m.ContractID
	}
	return ""
}

type AddAccountResponse struct {
	ContractID           string   `protobuf:"bytes,1,opt,name=contractID,proto3" json:"contractID,omitempty"`
	OperationLimit       int64    `protobuf:"varint,2,opt,name=operationLimit,proto3" json:"operationLimit,omitempty"`
	MonthLimit           int64    `protobuf:"varint,3,opt,name=monthLimit,proto3" json:"monthLimit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddAccountResponse) Reset()         { *m = AddAccountResponse{} }
func (m *AddAccountResponse) String() string { return proto.CompactTextString(m) }
func (*AddAccountResponse) ProtoMessage()    {}
func (*AddAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{1}
}

func (m *AddAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddAccountResponse.Unmarshal(m, b)
}
func (m *AddAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddAccountResponse.Marshal(b, m, deterministic)
}
func (m *AddAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddAccountResponse.Merge(m, src)
}
func (m *AddAccountResponse) XXX_Size() int {
	return xxx_messageInfo_AddAccountResponse.Size(m)
}
func (m *AddAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddAccountResponse proto.InternalMessageInfo

func (m *AddAccountResponse) GetContractID() string {
	if m != nil {
		return m.ContractID
	}
	return ""
}

func (m *AddAccountResponse) GetOperationLimit() int64 {
	if m != nil {
		return m.OperationLimit
	}
	return 0
}

func (m *AddAccountResponse) GetMonthLimit() int64 {
	if m != nil {
		return m.MonthLimit
	}
	return 0
}

type ListAccountsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{2}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

type ListAccountsResponse struct {
	ContractIDs          []string `protobuf:"bytes,1,rep,name=contractIDs,proto3" json:"contractIDs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsResponse) Reset()         { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()    {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{3}
}

func (m *ListAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsResponse.Unmarshal(m, b)
}
func (m *ListAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsResponse.Marshal(b, m, deterministic)
}
func (m *ListAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsResponse.Merge(m, src)
}
func (m *ListAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsResponse.Size(m)
}
func (m *ListAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsResponse proto.InternalMessageInfo

func (m *ListAccountsResponse) GetContractIDs() []string {
	if m != nil {
		return m.ContractIDs
	}
	return nil
}

type GetAccountBalancesRequest struct {
	ContractID           string   `protobuf:"bytes,1,opt,name=contractID,proto3" json:"contractID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountBalancesRequest) Reset()         { *m = GetAccountBalancesRequest{} }
func (m *GetAccountBalancesRequest) String() string { return proto.CompactTextString(m) }
func (*GetAccountBalancesRequest) ProtoMessage()    {}
func (*GetAccountBalancesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{4}
}

func (m *GetAccountBalancesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountBalancesRequest.Unmarshal(m, b)
}
func (m *GetAccountBalancesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountBalancesRequest.Marshal(b, m, deterministic)
}
func (m *GetAccountBalancesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountBalancesRequest.Merge(m, src)
}
func (m *GetAccountBalancesRequest) XXX_Size() int {
	return xxx_messageInfo_GetAccountBalancesRequest.Size(m)
}
func (m *GetAccountBalancesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountBalancesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountBalancesRequest proto.InternalMessageInfo

func (m *GetAccountBalancesRequest) GetContractID() string {
	if m != nil {
		return m.ContractID
	}
	return ""
}

type GetAccountBalancesResponse struct {
	Balance              int64    `protobuf:"varint,1,opt,name=balance,proto3" json:"balance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAccountBalancesResponse) Reset()         { *m = GetAccountBalancesResponse{} }
func (m *GetAccountBalancesResponse) String() string { return proto.CompactTextString(m) }
func (*GetAccountBalancesResponse) ProtoMessage()    {}
func (*GetAccountBalancesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{5}
}

func (m *GetAccountBalancesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAccountBalancesResponse.Unmarshal(m, b)
}
func (m *GetAccountBalancesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAccountBalancesResponse.Marshal(b, m, deterministic)
}
func (m *GetAccountBalancesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAccountBalancesResponse.Merge(m, src)
}
func (m *GetAccountBalancesResponse) XXX_Size() int {
	return xxx_messageInfo_GetAccountBalancesResponse.Size(m)
}
func (m *GetAccountBalancesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAccountBalancesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAccountBalancesResponse proto.InternalMessageInfo

func (m *GetAccountBalancesResponse) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

type DepositRequest struct {
	Amount               int64    `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositRequest) Reset()         { *m = DepositRequest{} }
func (m *DepositRequest) String() string { return proto.CompactTextString(m) }
func (*DepositRequest) ProtoMessage()    {}
func (*DepositRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{6}
}

func (m *DepositRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositRequest.Unmarshal(m, b)
}
func (m *DepositRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositRequest.Marshal(b, m, deterministic)
}
func (m *DepositRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositRequest.Merge(m, src)
}
func (m *DepositRequest) XXX_Size() int {
	return xxx_messageInfo_DepositRequest.Size(m)
}
func (m *DepositRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepositRequest proto.InternalMessageInfo

func (m *DepositRequest) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type DepositResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Amounts              []int64  `protobuf:"varint,2,rep,packed,name=amounts,proto3" json:"amounts,omitempty"`
	Comments             []string `protobuf:"bytes,3,rep,name=comments,proto3" json:"comments,omitempty"`
	ContractIDs          []string `protobuf:"bytes,4,rep,name=contractIDs,proto3" json:"contractIDs,omitempty"`
	Links                []string `protobuf:"bytes,5,rep,name=links,proto3" json:"links,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositResponse) Reset()         { *m = DepositResponse{} }
func (m *DepositResponse) String() string { return proto.CompactTextString(m) }
func (*DepositResponse) ProtoMessage()    {}
func (*DepositResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{7}
}

func (m *DepositResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositResponse.Unmarshal(m, b)
}
func (m *DepositResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositResponse.Marshal(b, m, deterministic)
}
func (m *DepositResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositResponse.Merge(m, src)
}
func (m *DepositResponse) XXX_Size() int {
	return xxx_messageInfo_DepositResponse.Size(m)
}
func (m *DepositResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DepositResponse proto.InternalMessageInfo

func (m *DepositResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DepositResponse) GetAmounts() []int64 {
	if m != nil {
		return m.Amounts
	}
	return nil
}

func (m *DepositResponse) GetComments() []string {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *DepositResponse) GetContractIDs() []string {
	if m != nil {
		return m.ContractIDs
	}
	return nil
}

func (m *DepositResponse) GetLinks() []string {
	if m != nil {
		return m.Links
	}
	return nil
}

type DepositCheckRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositCheckRequest) Reset()         { *m = DepositCheckRequest{} }
func (m *DepositCheckRequest) String() string { return proto.CompactTextString(m) }
func (*DepositCheckRequest) ProtoMessage()    {}
func (*DepositCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{8}
}

func (m *DepositCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositCheckRequest.Unmarshal(m, b)
}
func (m *DepositCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositCheckRequest.Marshal(b, m, deterministic)
}
func (m *DepositCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositCheckRequest.Merge(m, src)
}
func (m *DepositCheckRequest) XXX_Size() int {
	return xxx_messageInfo_DepositCheckRequest.Size(m)
}
func (m *DepositCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DepositCheckRequest proto.InternalMessageInfo

func (m *DepositCheckRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DepositCheckResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Status               bool     `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Amounts              []int64  `protobuf:"varint,3,rep,packed,name=amounts,proto3" json:"amounts,omitempty"`
	Comments             []string `protobuf:"bytes,4,rep,name=comments,proto3" json:"comments,omitempty"`
	ContractIDs          []string `protobuf:"bytes,5,rep,name=contractIDs,proto3" json:"contractIDs,omitempty"`
	Links                []string `protobuf:"bytes,6,rep,name=links,proto3" json:"links,omitempty"`
	Statuses             []bool   `protobuf:"varint,7,rep,packed,name=statuses,proto3" json:"statuses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepositCheckResponse) Reset()         { *m = DepositCheckResponse{} }
func (m *DepositCheckResponse) String() string { return proto.CompactTextString(m) }
func (*DepositCheckResponse) ProtoMessage()    {}
func (*DepositCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4cdcb2c5ad188f99, []int{9}
}

func (m *DepositCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepositCheckResponse.Unmarshal(m, b)
}
func (m *DepositCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepositCheckResponse.Marshal(b, m, deterministic)
}
func (m *DepositCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepositCheckResponse.Merge(m, src)
}
func (m *DepositCheckResponse) XXX_Size() int {
	return xxx_messageInfo_DepositCheckResponse.Size(m)
}
func (m *DepositCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DepositCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DepositCheckResponse proto.InternalMessageInfo

func (m *DepositCheckResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DepositCheckResponse) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *DepositCheckResponse) GetAmounts() []int64 {
	if m != nil {
		return m.Amounts
	}
	return nil
}

func (m *DepositCheckResponse) GetComments() []string {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *DepositCheckResponse) GetContractIDs() []string {
	if m != nil {
		return m.ContractIDs
	}
	return nil
}

func (m *DepositCheckResponse) GetLinks() []string {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *DepositCheckResponse) GetStatuses() []bool {
	if m != nil {
		return m.Statuses
	}
	return nil
}

func init() {
	proto.RegisterType((*AddAccountRequest)(nil), "protobuf.AddAccountRequest")
	proto.RegisterType((*AddAccountResponse)(nil), "protobuf.AddAccountResponse")
	proto.RegisterType((*ListAccountsRequest)(nil), "protobuf.ListAccountsRequest")
	proto.RegisterType((*ListAccountsResponse)(nil), "protobuf.ListAccountsResponse")
	proto.RegisterType((*GetAccountBalancesRequest)(nil), "protobuf.GetAccountBalancesRequest")
	proto.RegisterType((*GetAccountBalancesResponse)(nil), "protobuf.GetAccountBalancesResponse")
	proto.RegisterType((*DepositRequest)(nil), "protobuf.DepositRequest")
	proto.RegisterType((*DepositResponse)(nil), "protobuf.DepositResponse")
	proto.RegisterType((*DepositCheckRequest)(nil), "protobuf.DepositCheckRequest")
	proto.RegisterType((*DepositCheckResponse)(nil), "protobuf.DepositCheckResponse")
}

func init() { proto.RegisterFile("qiwi.proto", fileDescriptor_4cdcb2c5ad188f99) }

var fileDescriptor_4cdcb2c5ad188f99 = []byte{
	// 485 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0xcd, 0x8e, 0xd3, 0x30,
	0x10, 0xde, 0xd4, 0xfd, 0x1d, 0xa0, 0x08, 0x6f, 0x59, 0x79, 0x03, 0xac, 0x22, 0xf3, 0xa3, 0x9e,
	0x7a, 0x00, 0x09, 0x21, 0x71, 0x61, 0xcb, 0x4a, 0xa8, 0xd2, 0x4a, 0x2c, 0x79, 0x83, 0x34, 0x35,
	0x5a, 0xab, 0x1b, 0xbb, 0x5b, 0xbb, 0xda, 0x0b, 0xef, 0xc0, 0x95, 0x47, 0xe2, 0xb1, 0x90, 0x1d,
	0x27, 0x71, 0xd3, 0xa4, 0x9c, 0xa2, 0x99, 0xf9, 0xe6, 0x9b, 0xf9, 0x3c, 0x5f, 0x00, 0xee, 0xf9,
	0x03, 0x9f, 0x6d, 0xb6, 0x52, 0x4b, 0x3c, 0xb4, 0x9f, 0xe5, 0xee, 0x27, 0x5d, 0xc0, 0xb3, 0xcb,
	0xd5, 0xea, 0x32, 0x4d, 0xe5, 0x4e, 0xe8, 0x98, 0xdd, 0xef, 0x98, 0xd2, 0x78, 0x02, 0x3d, 0x2d,
	0xd7, 0x4c, 0x90, 0x20, 0x0a, 0xa6, 0xa3, 0x38, 0x0f, 0xf0, 0x05, 0x40, 0x2a, 0x85, 0xde, 0x26,
	0xa9, 0x5e, 0x5c, 0x91, 0x8e, 0x2d, 0x79, 0x19, 0xfa, 0x0b, 0xb0, 0x4f, 0xa5, 0x36, 0x52, 0x28,
	0x56, 0xeb, 0x0a, 0xea, 0x5d, 0xf8, 0x1d, 0x8c, 0xe5, 0x86, 0x6d, 0x13, 0xcd, 0xa5, 0xb8, 0xe6,
	0x19, 0xd7, 0x96, 0x19, 0xc5, 0xb5, 0xac, 0xe1, 0xc9, 0xa4, 0xd0, 0xb7, 0x39, 0x06, 0x59, 0x8c,
	0x97, 0xa1, 0xcf, 0xe1, 0xf4, 0x9a, 0x2b, 0xed, 0xc6, 0x2b, 0x27, 0x85, 0x7e, 0x82, 0xc9, 0x7e,
	0xda, 0xad, 0x15, 0xc1, 0xa3, 0x6a, 0x09, 0x45, 0x82, 0x08, 0x4d, 0x47, 0xb1, 0x9f, 0xa2, 0x9f,
	0xe1, 0xfc, 0x1b, 0x2b, 0x1a, 0xe7, 0xc9, 0x5d, 0x22, 0x52, 0x56, 0xd0, 0xfe, 0x4f, 0x15, 0xfd,
	0x08, 0x61, 0x53, 0xb3, 0x1b, 0x4e, 0x60, 0xb0, 0xcc, 0x73, 0xb6, 0x15, 0xc5, 0x45, 0x48, 0xa7,
	0x30, 0xbe, 0x62, 0x1b, 0xa9, 0x78, 0x79, 0x8b, 0x33, 0xe8, 0x27, 0x99, 0x61, 0x71, 0x50, 0x17,
	0xd1, 0xdf, 0x01, 0x3c, 0x2d, 0xa1, 0x8e, 0x77, 0x0c, 0x1d, 0xbe, 0x72, 0xdb, 0x74, 0xf8, 0xca,
	0xcc, 0xc9, 0xd1, 0x8a, 0x74, 0x22, 0x64, 0xe6, 0xb8, 0x10, 0x87, 0x30, 0x4c, 0x65, 0x96, 0x31,
	0x53, 0x42, 0x56, 0x7b, 0x19, 0xd7, 0x9f, 0xa6, 0x7b, 0xf0, 0x34, 0xc6, 0x1f, 0x77, 0x5c, 0xac,
	0x15, 0xe9, 0xd9, 0x5a, 0x1e, 0xd0, 0xb7, 0x70, 0xea, 0x16, 0xfa, 0x7a, 0xcb, 0xd2, 0x75, 0x21,
	0xa0, 0xb6, 0x14, 0xfd, 0x1b, 0xc0, 0x64, 0x1f, 0xd7, 0xb2, 0xfd, 0x19, 0xf4, 0x95, 0x4e, 0xf4,
	0x4e, 0x59, 0x47, 0x0c, 0x63, 0x17, 0xf9, 0xaa, 0x50, 0xbb, 0xaa, 0xee, 0x71, 0x55, 0xbd, 0x23,
	0xaa, 0xfa, 0x9e, 0x2a, 0xc3, 0x99, 0xcf, 0x65, 0x8a, 0x0c, 0x22, 0x34, 0x1d, 0xc6, 0x65, 0xfc,
	0xfe, 0x0f, 0x82, 0xee, 0x0f, 0xfe, 0xc0, 0xf1, 0x02, 0xa0, 0xb2, 0x3e, 0x7e, 0x31, 0x2b, 0x7e,
	0xaf, 0xd9, 0xc1, 0xbf, 0x15, 0xbe, 0x6c, 0x2e, 0xe6, 0x6f, 0x40, 0x4f, 0xf0, 0x77, 0x78, 0xec,
	0x1b, 0x16, 0xbf, 0xaa, 0xf0, 0x0d, 0xfe, 0x0e, 0x2f, 0xda, 0xca, 0x25, 0x61, 0x02, 0xf8, 0xd0,
	0x8a, 0xf8, 0x75, 0xd5, 0xd7, 0xea, 0xf2, 0xf0, 0xcd, 0x71, 0x50, 0x39, 0xe2, 0x0b, 0x0c, 0xdc,
	0x45, 0x31, 0xa9, 0x5a, 0xf6, 0x8d, 0x1c, 0x9e, 0x37, 0x54, 0x7c, 0xd5, 0xbe, 0x27, 0x7c, 0xd5,
	0x0d, 0x9e, 0xf2, 0x55, 0x37, 0x59, 0x89, 0x9e, 0xcc, 0x9f, 0xcc, 0x47, 0xe6, 0x32, 0x37, 0x06,
	0x76, 0x13, 0x2c, 0xfb, 0x16, 0xff, 0xe1, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcb, 0xf9, 0x12,
	0x04, 0x05, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QiwiClient is the client API for Qiwi service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QiwiClient interface {
	AddAccount(ctx context.Context, in *AddAccountRequest, opts ...grpc.CallOption) (*AddAccountResponse, error)
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
	GetAccountBalances(ctx context.Context, in *GetAccountBalancesRequest, opts ...grpc.CallOption) (*GetAccountBalancesResponse, error)
	//  rpc SendMoneyToQiwi (SendMoneyToQiwiRequest) returns (SendMoneyToQiwiResponse) {} DEPRECATED
	Deposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error)
	DepositCheck(ctx context.Context, in *DepositCheckRequest, opts ...grpc.CallOption) (*DepositCheckResponse, error)
}

type qiwiClient struct {
	cc *grpc.ClientConn
}

func NewQiwiClient(cc *grpc.ClientConn) QiwiClient {
	return &qiwiClient{cc}
}

func (c *qiwiClient) AddAccount(ctx context.Context, in *AddAccountRequest, opts ...grpc.CallOption) (*AddAccountResponse, error) {
	out := new(AddAccountResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Qiwi/AddAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qiwiClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Qiwi/ListAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qiwiClient) GetAccountBalances(ctx context.Context, in *GetAccountBalancesRequest, opts ...grpc.CallOption) (*GetAccountBalancesResponse, error) {
	out := new(GetAccountBalancesResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Qiwi/GetAccountBalances", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qiwiClient) Deposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error) {
	out := new(DepositResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Qiwi/Deposit", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qiwiClient) DepositCheck(ctx context.Context, in *DepositCheckRequest, opts ...grpc.CallOption) (*DepositCheckResponse, error) {
	out := new(DepositCheckResponse)
	err := c.cc.Invoke(ctx, "/protobuf.Qiwi/DepositCheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QiwiServer is the server API for Qiwi service.
type QiwiServer interface {
	AddAccount(context.Context, *AddAccountRequest) (*AddAccountResponse, error)
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	GetAccountBalances(context.Context, *GetAccountBalancesRequest) (*GetAccountBalancesResponse, error)
	//  rpc SendMoneyToQiwi (SendMoneyToQiwiRequest) returns (SendMoneyToQiwiResponse) {} DEPRECATED
	Deposit(context.Context, *DepositRequest) (*DepositResponse, error)
	DepositCheck(context.Context, *DepositCheckRequest) (*DepositCheckResponse, error)
}

func RegisterQiwiServer(s *grpc.Server, srv QiwiServer) {
	s.RegisterService(&_Qiwi_serviceDesc, srv)
}

func _Qiwi_AddAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QiwiServer).AddAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Qiwi/AddAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QiwiServer).AddAccount(ctx, req.(*AddAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qiwi_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QiwiServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Qiwi/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QiwiServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qiwi_GetAccountBalances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAccountBalancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QiwiServer).GetAccountBalances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Qiwi/GetAccountBalances",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QiwiServer).GetAccountBalances(ctx, req.(*GetAccountBalancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qiwi_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QiwiServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Qiwi/Deposit",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QiwiServer).Deposit(ctx, req.(*DepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Qiwi_DepositCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QiwiServer).DepositCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.Qiwi/DepositCheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QiwiServer).DepositCheck(ctx, req.(*DepositCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Qiwi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.Qiwi",
	HandlerType: (*QiwiServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddAccount",
			Handler:    _Qiwi_AddAccount_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _Qiwi_ListAccounts_Handler,
		},
		{
			MethodName: "GetAccountBalances",
			Handler:    _Qiwi_GetAccountBalances_Handler,
		},
		{
			MethodName: "Deposit",
			Handler:    _Qiwi_Deposit_Handler,
		},
		{
			MethodName: "DepositCheck",
			Handler:    _Qiwi_DepositCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qiwi.proto",
}
